# Generated by Django 4.0.3 on 2022-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_email_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
