# Generated by Django 4.0.3 on 2022-03-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_email_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_sent',
        ),
    ]
