# Generated by Django 4.0.3 on 2022-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_email_is_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(editable=False, max_length=256, verbose_name='Receiver Email')),
                ('subject', models.CharField(editable=False, max_length=256, verbose_name='Subject')),
                ('body', models.CharField(editable=False, max_length=1500, verbose_name='Body')),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
