# Generated by Django 4.0.3 on 2022-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_email_log_delete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_log',
            name='body',
            field=models.CharField(max_length=1500, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='email_log',
            name='email',
            field=models.CharField(max_length=256, verbose_name='Receiver Email'),
        ),
        migrations.AlterField(
            model_name='email_log',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='Subject'),
        ),
    ]
